version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Ab@12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet

  webstudio:
    image: ${DOCKER_REGISTRY-}webstudio
    build:
      context: .
      dockerfile: webStudio/Dockerfile
    ports:
      - "80:8080"
      - "443:8081"
    volumes:
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https:ro
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /root/.aspnet/https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: Pass123!
       - ./keys:/keys
    depends_on:
      - sqlserver
      - migrate
    networks:
      - appnet
    
  migrate:
    build:
      context: .
      dockerfile: webStudio/Dockerfile
    command: >
      sh -c "dotnet ef database update --project webStudio --startup-project webStudio"
    depends_on:
      - sqlserver
    networks:
      - appnet
  
networks:
  appnet:
